[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pda_task_1 = "Fe1qa64RN7rRXV8DBFZB6y5UDrgqF9UwxtKFTQ52oNzF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/igorswierczynski/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
